### ISSUE TITLE
Creation portal

### ISSUE THREAD

**Issue by PixelmonPRO** [Zerthick/NoPortal#1]
Hello! Test plugin in SF 3206, and have bug: https://gyazo.com/b9d80ebffc4f76dd195dfa8386e46ad2 (no errors in console)
Request: add new permission, which will prohibit entering the existing portal.
Thanks!)

**Comment by Zerthick** [comment]
This appears to be a bug in sponge, I'll see if I can add that permission in in the meantime 😄

**Comment by Zerthick** [comment]
I've added the `noportal.enter` permission in the latest release: https://github.com/Zerthick/NoPortal/releases/tag/v1.1.0
